service: garden-aid-chat-bff
provider:
  name: aws
  runtime: nodejs4.3
package:
  include:
    - index.js
    - src
    - node_modules
  exclude:
    - tests
    - coverage
    - package.json
functions:
  slackNotify:
      handler: index.notify
      events:
        - sns: ${slackNotifySnsTopicName}
