service: garden-aid-chat-bff
provider:
  name: aws
  runtime: nodejs4.3
package:
  include:
    - node_modules
    - src
  exclude:
    - coverage
    - tests
    - .editorconfig
    - .eslintignore
    - .gitignore
    - .synk
    - .travis.yml
    - .create-secrets.js
    - deploy.sh
    - LICENSE
    - package.json
    - README.md

functions:
  slackNotify:
      handler: index.notify
      events:
        - sns: ${slackNotifySnsTopicName}
